// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BannerChangeController from "./banner_change_controller"
application.register("banner-change", BannerChangeController)

import ChartBisController from "./chart_bis_controller"
application.register("chart-bis", ChartBisController)

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import DeviseModalController from "./devise_modal_controller"
application.register("devise-modal", DeviseModalController)

import ExperienceController from "./experience_controller"
application.register("experience", ExperienceController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import NestedFormController from "./nested_form_controller"
application.register("nested-form", NestedFormController)

import SearchToggleController from "./search_toggle_controller"
application.register("search-toggle", SearchToggleController)

import SliderController from "./slider_controller"
application.register("slider", SliderController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)

import { Application } from '@hotwired/stimulus'
import Notification from 'stimulus-notification'

const application = Application.start()
application.register('notification', Notification)
